# yaml-language-server: https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

tasks:
  clean:
    cmds:
      - rm -rf dist
      - mkdir -p dist/artifacts

  build-apk:
    internal: true
    dir: android
    cmds:
      - chmod +x gradlew
      - ./gradlew :app:assembleRelease -x test
      - rm {{.RELEASE_DIR}}/app-release-unsigned-aligned.apk || true
      - zipalign -v -p 4 {{.RELEASE_DIR}}/app-release-unsigned.apk {{.RELEASE_DIR}}/app-release-unsigned-aligned.apk
      - echo $ANDROID_KEYSTORE | base64 --decode > my-release-key.jks
      - apksigner sign --ks my-release-key.jks --ks-pass env:ANDROID_KEYSTORE_PASSWORD --out {{.RELEASE_DIR}}/app-release.apk {{.RELEASE_DIR}}/app-release-unsigned-aligned.apk
      - apksigner verify {{.RELEASE_DIR}}/app-release.apk
      - cp {{.RELEASE_DIR}}/app-release.apk ../dist/radiomuxplayer-release.apk
    vars:
      RELEASE_DIR: app/build/outputs/apk/release
    env:
      ANDROID_KEYSTORE:
      ANDROID_KEYSTORE_PASSWORD:

  build-apk-debug:
    internal: true
    dir: android
    cmds:
      - chmod +x gradlew
      - ./gradlew :app:assembleDebug -x test
      - cp {{.DEBUG_DIR}}/app-debug.apk ../dist/radiomuxplayer-debug.apk
    vars:
      DEBUG_DIR: app/build/outputs/apk/debug

  build-server:
    internal: true
    cmds:
      - go mod tidy
      - go generate ./...
      - GOOS=linux GOARCH=amd64       go build -ldflags="{{.LDFLAGS}}" -o ./dist/radiomux_Linux_x86_64       {{.MAIN_PACKAGE}}
      - GOOS=linux GOARCH=arm GOARM=7 go build -ldflags="{{.LDFLAGS}}" -o ./dist/radiomux_Linux_armv7        {{.MAIN_PACKAGE}}
      - GOOS=linux GOARCH=arm64       go build -ldflags="{{.LDFLAGS}}" -o ./dist/radiomux_Linux_arm64        {{.MAIN_PACKAGE}}
      - GOOS=darwin GOARCH=arm64      go build -ldflags="{{.LDFLAGS}}" -o ./dist/radiomux_Darwin_arm64       {{.MAIN_PACKAGE}}
      - GOOS=windows GOARCH=amd64     go build -ldflags="{{.LDFLAGS}}" -o ./dist/radiomux_Windows_x86_64.exe {{.MAIN_PACKAGE}}
    env:
      CGO_ENABLED: 0
    vars:
      PACKAGE_NAME: "github.com/ItsNotGoodName/radiomux"

      BUILD_PACKAGE_NAME: "{{.PACKAGE_NAME}}/internal/build/build"
      BUILD_VERSION: "nightly"
      BUILD_DATE: '{{now | date "2006-01-02T15:04:05Z07:00"}}'
      BUILD_COMMIT:
        sh: git rev-parse HEAD
      BUILD_REPO_URL: "https://{{.PACKAGE_NAME}}"

      LDFLAGS: -s -w -X {{.BUILD_PACKAGE_NAME}}.Version={{.BUILD_VERSION}} -X {{.BUILD_PACKAGE_NAME}}.Commit={{.BUILD_COMMIT}} -X {{.BUILD_PACKAGE_NAME}}.Date={{.BUILD_DATE}} -X {{.BUILD_PACKAGE_NAME}}.RepoURL={{.BUILD_REPO_URL}}
      MAIN_PACKAGE: "{{.PACKAGE_NAME}}/cmd/radiomux"

  compile-artifacts:
    internal: true
    dir: dist
    cmds:
      - cp *.apk artifacts/
      - for: { var: FILES }
        cmd: cp ../{{.ITEM}} .
      - for: { var: WINDOWS_FILES }
        cmd: cp ../{{.ITEM}} .
      - tar -czf artifacts/radiomux_Linux_x86_64.tar.gz radiomux_Linux_x86_64       {{.FILES}}
      - tar -czf artifacts/radiomux_Linux_armv7.tar.gz  radiomux_Linux_armv7        {{.FILES}}
      - tar -czf artifacts/radiomux_Linux_arm64.tar.gz  radiomux_Linux_arm64        {{.FILES}}
      - tar -czf artifacts/radiomux_Darwin_arm64.tar.gz radiomux_Darwin_arm64       {{.FILES}}
      - zip -q artifacts/radiomux_Windows_x86_64.zip    radiomux_Windows_x86_64.exe {{.FILES}} {{.WINDOWS_FILES}}
      - cd artifacts && sha256sum *.tar.gz *.zip *.apk > checksum.txt
    vars:
      FILES: README.md LICENSE
      WINDOWS_FILES: WinSW.xml

  build:
    deps: [clean, build-apk, build-server]
    dir: dist
    cmds:
      - task: compile-artifacts

  build-debug:
    deps: [clean, build-apk-debug, build-server]
    dir: dist
    cmds:
      - task: compile-artifacts
