# yaml-language-server: https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

vars:
  CMD_NAME: radiomux
  PACKAGE_NAME: "github.com/ItsNotGoodName/radiomux"
  APK_NAME: radiomuxplayer

tasks:
  clean:
    cmds:
      - rm -rf dist
      - mkdir dist dist/artifacts dist/files dist/files-windows

  build-apk:
    internal: true
    dir: android
    cmds:
      - chmod +x gradlew
      - ./gradlew :app:assembleRelease -x test
      - rm {{.RELEASE_DIR}}/app-release-unsigned-aligned.apk || true
      - zipalign -v -p 4 {{.RELEASE_DIR}}/app-release-unsigned.apk {{.RELEASE_DIR}}/app-release-unsigned-aligned.apk
      - echo $ANDROID_KEYSTORE | base64 --decode > my-release-key.jks
      - apksigner sign --ks my-release-key.jks --ks-pass env:ANDROID_KEYSTORE_PASSWORD --out {{.RELEASE_DIR}}/app-release.apk {{.RELEASE_DIR}}/app-release-unsigned-aligned.apk
      - apksigner verify {{.RELEASE_DIR}}/app-release.apk
      - cp {{.RELEASE_DIR}}/app-release.apk ../dist/{{.APK_NAME}}-release.apk
    vars:
      RELEASE_DIR: app/build/outputs/apk/release
    env:
      ANDROID_KEYSTORE:
      ANDROID_KEYSTORE_PASSWORD:

  build-apk-debug:
    internal: true
    dir: android
    cmds:
      - chmod +x gradlew
      - ./gradlew :app:assembleDebug -x test
      - cp {{.DEBUG_DIR}}/app-debug.apk ../dist/{{.APK_NAME}}-debug.apk
    vars:
      DEBUG_DIR: app/build/outputs/apk/debug

  build-server:
    internal: true
    cmds:
      - go mod tidy
      - go generate ./...
      - GOOS=linux GOARCH=amd64       go build -ldflags="{{.MAIN_LDFLAGS}}" -o ./dist/{{.CMD_NAME}}_Linux_x86_64/{{.CMD_NAME}}       {{.MAIN_PACKAGE}}
      - GOOS=linux GOARCH=arm GOARM=7 go build -ldflags="{{.MAIN_LDFLAGS}}" -o ./dist/{{.CMD_NAME}}_Linux_armv7/{{.CMD_NAME}}        {{.MAIN_PACKAGE}}
      - GOOS=linux GOARCH=arm64       go build -ldflags="{{.MAIN_LDFLAGS}}" -o ./dist/{{.CMD_NAME}}_Linux_arm64/{{.CMD_NAME}}        {{.MAIN_PACKAGE}}
      - GOOS=darwin GOARCH=arm64      go build -ldflags="{{.MAIN_LDFLAGS}}" -o ./dist/{{.CMD_NAME}}_Darwin_arm64/{{.CMD_NAME}}       {{.MAIN_PACKAGE}}
      - GOOS=windows GOARCH=amd64     go build -ldflags="{{.MAIN_LDFLAGS}}" -o ./dist/{{.CMD_NAME}}_Windows_x86_64/{{.CMD_NAME}}.exe {{.MAIN_PACKAGE}}
    env:
      CGO_ENABLED: 0
    vars:
      BUILD_PACKAGE_NAME: "{{.PACKAGE_NAME}}/internal/build"
      BUILD_VERSION: "nightly"
      BUILD_DATE: '{{now | date "2006-01-02T15:04:05Z07:00"}}'
      BUILD_COMMIT:
        sh: git rev-parse HEAD
      BUILD_REPO_URL: "https://{{.PACKAGE_NAME}}"

      MAIN_LDFLAGS: -s -w -X {{.BUILD_PACKAGE_NAME}}.version={{.BUILD_VERSION}} -X {{.BUILD_PACKAGE_NAME}}.commit={{.BUILD_COMMIT}} -X {{.BUILD_PACKAGE_NAME}}.date={{.BUILD_DATE}} -X {{.BUILD_PACKAGE_NAME}}.repoURL={{.BUILD_REPO_URL}}
      MAIN_PACKAGE: "{{.PACKAGE_NAME}}/cmd/{{.CMD_NAME}}"

  compile-artifacts:
    internal: true
    dir: dist
    cmds:
      - cp *.apk artifacts/
      - for: { var: FILES }
        cmd: cp ../{{.ITEM}} "./files/$(basename {{.ITEM}})"
      - for: { var: WINDOWS_FILES }
        cmd: cp ../{{.ITEM}} "./files-windows/$(basename {{.ITEM}})"
      - cd {{.CMD_NAME}}_Linux_x86_64   && cp ../files/* . &&                            tar -czf ../artifacts/{{.CMD_NAME}}_Linux_x86_64.tar.gz *
      - cd {{.CMD_NAME}}_Linux_armv7    && cp ../files/* . &&                            tar -czf ../artifacts/{{.CMD_NAME}}_Linux_armv7.tar.gz  *
      - cd {{.CMD_NAME}}_Linux_arm64    && cp ../files/* . &&                            tar -czf ../artifacts/{{.CMD_NAME}}_Linux_arm64.tar.gz  *
      - cd {{.CMD_NAME}}_Darwin_arm64   && cp ../files/* . &&                            tar -czf ../artifacts/{{.CMD_NAME}}_Darwin_arm64.tar.gz *
      - cd {{.CMD_NAME}}_Windows_x86_64 && cp ../files/* . && cp ../files-windows/* . && zip -q   ../artifacts/{{.CMD_NAME}}_Windows_x86_64.zip  *
      - cd artifacts && sha256sum *.tar.gz *.zip *.apk > checksum.txt
    vars:
      FILES: README.md LICENSE
      WINDOWS_FILES: WinSW.xml

  build:
    deps: [clean, build-apk, build-server]
    dir: dist
    cmds:
      - task: compile-artifacts

  build-debug:
    deps: [clean, build-apk-debug, build-server]
    dir: dist
    cmds:
      - task: compile-artifacts
