/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/players/{id}/play": {
    post: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description OK */
        204: {
          content: never;
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/players/{id}/pause": {
    post: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description OK */
        204: {
          content: never;
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/players/{id}/stop": {
    post: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description OK */
        204: {
          content: never;
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/players/{id}/seek": {
    post: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description OK */
        204: {
          content: never;
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/players/{id}/volume": {
    post: {
      parameters: {
        query?: {
          delta?: number;
          mute?: boolean;
        };
        path: {
          id: number;
        };
      };
      responses: {
        /** @description OK */
        204: {
          content: never;
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/players/{id}/media": {
    post: {
      parameters: {
        query: {
          uri: string;
        };
        path: {
          id: number;
        };
      };
      responses: {
        /** @description OK */
        204: {
          content: never;
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/players/{id}/preset": {
    post: {
      parameters: {
        query: {
          preset: number;
        };
        path: {
          id: number;
        };
      };
      responses: {
        /** @description OK */
        204: {
          content: never;
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/players": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["Player"][];
          };
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    /** @description Create player */
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
          };
        };
      };
      responses: {
        /** @description OK */
        201: {
          content: {
            "application/json": components["schemas"]["Player"];
          };
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["Player"][];
          };
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/players/{id}": {
    /** @description Get player by id */
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["Player"];
          };
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    /** @description Update player by id */
    post: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            name?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Player"];
          };
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        204: {
          content: {
            "application/json": components["schemas"]["Player"];
          };
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/presets": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["Preset"][];
          };
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    /** @description Create preset */
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            url: string;
          };
        };
      };
      responses: {
        /** @description OK */
        201: {
          content: {
            "application/json": components["schemas"]["Preset"];
          };
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["Preset"][];
          };
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/presets/{id}": {
    /** @description Get preset by id */
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["Preset"];
          };
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    /** @description Update preset by id */
    post: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            name?: string;
            url?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Preset"];
          };
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        204: {
          content: {
            "application/json": components["schemas"]["Preset"];
          };
        };
        /** @description unexpected error */
        default: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Error: {
      message: string;
    };
    Player: {
      /** Format: int64 */
      id: number;
      name: string;
      token: string;
    };
    Preset: {
      /** Format: int64 */
      id: number;
      name: string;
      url: string;
    };
    Event: unknown;
    EventBase: {
      type: components["schemas"]["EventType"];
    };
    /** @enum {string} */
    EventType: "player_state" | "player_state_partial";
    EventDataPlayerStatePartial: unknown;
    EventDataPlayerState: unknown;
    /** @enum {integer} */
    PlayerPlaybackState: 1 | 2 | 3 | 4;
    PlayerStatePartial: {
      /** Format: int64 */
      id: number;
      name?: string;
      connected?: boolean;
      ready?: boolean;
      min_volume?: number;
      max_volume?: number;
      volume?: number;
      muted?: boolean;
      playback_state?: components["schemas"]["PlayerPlaybackState"];
      playback_error?: string;
      playing?: boolean;
      loading?: boolean;
      title?: string;
      genre?: string;
      station?: string;
      uri?: string;
    };
    PlayerState: components["schemas"]["PlayerStatePartial"] & Record<string, never>;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
