// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package openapi

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for EventType.
const (
	EventTypePlayerState        EventType = "player_state"
	EventTypePlayerStatePartial EventType = "player_state_partial"
)

// Defines values for PlayerPlaybackState.
const (
	BUFFERING PlayerPlaybackState = "BUFFERING"
	ENDED     PlayerPlaybackState = "ENDED"
	IDLE      PlayerPlaybackState = "IDLE"
	READY     PlayerPlaybackState = "READY"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Event defines model for Event.
type Event struct {
	union json.RawMessage
}

// EventBase defines model for EventBase.
type EventBase struct {
	Type EventType `json:"type"`
}

// EventDataPlayerState defines model for EventDataPlayerState.
type EventDataPlayerState struct {
	Data []PlayerState `json:"data"`
	Type EventType     `json:"type"`
}

// EventDataPlayerStatePartial defines model for EventDataPlayerStatePartial.
type EventDataPlayerStatePartial struct {
	Data []PlayerStatePartial `json:"data"`
	Type EventType            `json:"type"`
}

// EventType defines model for EventType.
type EventType string

// PlayerPlaybackState defines model for PlayerPlaybackState.
type PlayerPlaybackState string

// PlayerState defines model for PlayerState.
type PlayerState struct {
	Connected     bool                `json:"connected"`
	Genre         string              `json:"genre"`
	Id            int64               `json:"id"`
	Loading       bool                `json:"loading"`
	MaxVolume     int                 `json:"max_volume"`
	MinVolume     int                 `json:"min_volume"`
	Muted         bool                `json:"muted"`
	Name          string              `json:"name"`
	PlaybackError string              `json:"playback_error"`
	PlaybackState PlayerPlaybackState `json:"playback_state"`
	Playing       bool                `json:"playing"`
	Ready         bool                `json:"ready"`
	Station       string              `json:"station"`
	Title         string              `json:"title"`
	Uri           string              `json:"uri"`
	Volume        int                 `json:"volume"`
}

// PlayerStatePartial defines model for PlayerStatePartial.
type PlayerStatePartial struct {
	Connected     *bool                `json:"connected,omitempty"`
	Genre         *string              `json:"genre,omitempty"`
	Id            int64                `json:"id"`
	Loading       *bool                `json:"loading,omitempty"`
	MaxVolume     *int                 `json:"max_volume,omitempty"`
	MinVolume     *int                 `json:"min_volume,omitempty"`
	Muted         *bool                `json:"muted,omitempty"`
	Name          *string              `json:"name,omitempty"`
	PlaybackError *string              `json:"playback_error,omitempty"`
	PlaybackState *PlayerPlaybackState `json:"playback_state,omitempty"`
	Playing       *bool                `json:"playing,omitempty"`
	Ready         *bool                `json:"ready,omitempty"`
	Station       *string              `json:"station,omitempty"`
	Title         *string              `json:"title,omitempty"`
	Uri           *string              `json:"uri,omitempty"`
	Volume        *int                 `json:"volume,omitempty"`
}

// AsEventDataPlayerState returns the union data inside the Event as a EventDataPlayerState
func (t Event) AsEventDataPlayerState() (EventDataPlayerState, error) {
	var body EventDataPlayerState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventDataPlayerState overwrites any union data inside the Event as the provided EventDataPlayerState
func (t *Event) FromEventDataPlayerState(v EventDataPlayerState) error {
	v.Type = "player_state"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventDataPlayerState performs a merge with any union data inside the Event, using the provided EventDataPlayerState
func (t *Event) MergeEventDataPlayerState(v EventDataPlayerState) error {
	v.Type = "player_state"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsEventDataPlayerStatePartial returns the union data inside the Event as a EventDataPlayerStatePartial
func (t Event) AsEventDataPlayerStatePartial() (EventDataPlayerStatePartial, error) {
	var body EventDataPlayerStatePartial
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventDataPlayerStatePartial overwrites any union data inside the Event as the provided EventDataPlayerStatePartial
func (t *Event) FromEventDataPlayerStatePartial(v EventDataPlayerStatePartial) error {
	v.Type = "player_state_partial"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventDataPlayerStatePartial performs a merge with any union data inside the Event, using the provided EventDataPlayerStatePartial
func (t *Event) MergeEventDataPlayerStatePartial(v EventDataPlayerStatePartial) error {
	v.Type = "player_state_partial"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t Event) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Event) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "player_state":
		return t.AsEventDataPlayerState()
	case "player_state_partial":
		return t.AsEventDataPlayerStatePartial()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Event) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Event) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /players/{id}/qr)
	GetPlayersIdQr(ctx echo.Context, id int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetPlayersIdQr converts echo context to params.
func (w *ServerInterfaceWrapper) GetPlayersIdQr(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPlayersIdQr(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/players/:id/qr", wrapper.GetPlayersIdQr)

}
